[package]
name = "ds-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
