version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      tokio:
        patterns:
          - "tokio*"
      axum:
        patterns:
          - "axum*"
          - "tower*"
          - "hyper*"
      security:
        patterns:
          - "argon2"
          - "jsonwebtoken"
          - "rustls*"
    labels:
      - "dependencies"
      - "rust"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "ci"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/crates/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "dependencies"
      - "docker"
