version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: crates/api/Dockerfile
    image: deepersensor/api:dev
    env_file:
      - ./.env
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/deepersensor
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - ollama
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deepersensor
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_models:/root/.ollama
    expose:
      - "11434"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: deepersensor/nginx:dev
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx

volumes:
  ollama_models: {}
